<?php
echo '$_POST';
var_dump($_POST);
var_dump($_SERVER);
if ($_SERVER["REQUEST_METHOD"] == "POST") {
    echo 'POST request received';
    $first_name = isset($_POST['first_name']) ? htmlspecialchars($_POST['first_name']) : '';
    $last_name = isset($_POST['last_name']) ? htmlspecialchars($_POST['last_name']) : '';
    $email = isset($_POST['email']) ? htmlspecialchars($_POST['email']) : '';
    $when_it_happened = isset($_POST['when_it_happened']) ? htmlspecialchars($_POST['when_it_happened']) : '';
    $how_long = isset($_POST['how_long']) ? htmlspecialchars($_POST['how_long']) : '';
    $how_many = isset($_POST['how_many']) ? htmlspecialchars($_POST['how_many']) : '';
    $what_they_did = isset($_POST['what_they_did']) ? htmlspecialchars($_POST['what_they_did']) : '';
    $what_they_looked_like = isset($_POST['what_they_looked_like']) ? htmlspecialchars($_POST['what_they_looked_like']) : '';
    $have_you_seen_my_dog = isset($_POST['have_you_seen_my_dog']) ? htmlspecialchars($_POST['have_you_seen_my_dog']) : '';

    $output_string = $first_name . ' ' . $last_name . ' ' . $email . ' ' . $when_it_happened . ' ' . $how_long . ' ' . $how_many . ' ' . $what_they_did . ' ' . $what_they_looked_like . ' ' . $have_you_seen_my_dog . "\n";
    var_dump($output_string);
    try {
        $filename = 'report.txt';
        file_put_contents($filename, $output_string, FILE_APPEND);
        # echo "Report submitted successfully";
    } catch (Exception $e) {
        var_dump($e);
        error_log("Error: " . $e->getMessage());
        #  echo $e->getMessage();

    }
}
?>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Aliens Abducted Me - Report an Abduction</title>
</head>
<body>
<h2>Aliens Abducted Me - Report an Abduction</h2>
</body>
</html>